### PR TITLE
Fix formatted phone number issue for pm command

### LINKED ISSUE #395: Allow Telegram formatted phone number for 'pm' command
At now `pm` command require plain phone number in format `pm +12345678901` or `pm 12345678901`. But in Telegram web interface numbers are shown in formatted style like `+1 (234) 567-89-01`, so users can't quickly copy-paste number, but need to manually remove formatting.

For simplify this process will be good to allow accept phone numbers in telegram format `+1 (234) 567-89-01` for `pm` command too.

Also will be good to describe in `help` command format of `pm <identifier>` value for phone string (with `+` or without too?) and username (with `@` or without?).

### PR DESCRIPTION
**Pull request by thesseyren**
Fixes #395 
 - It just merges event arguments and removes some special characters from the string.
 - I think there is no need to add an additional description to `help` command.

Thanks.

### CODE REVIEW

**Comment by djdomi** [comment]
> Fixes #395
> 
> * It just merges event arguments and removes some special characters from the string.
> * I think there is no need to add an additional description to `help` command.
> 
> Thanks.

i please to update ALL commands, as they do not descripe howto use.

**Comment by thesseyren** [comment]
@djdomi so, do you want me to fix this issue for all of the commands that requires phone number?

**Comment by djdomi** [comment]
yes, as mostly each command (even not this specific one) comes only with an "I already know what this command does" description

**Comment by thesseyren** [comment]
Is there any different command that requires phone number?

**Comment by tulir** [comment]
The `pm` command accepting formatted numbers has a decent use case as described in the issue, but the register one is a bit too hacky, so I'll just merge the first commit.

**Pull request closed without merging**
