### PR TITLE
Add personal filtering communities

### LINKED ISSUE #365: Add support for creating personal filtering spaces
Feature request:

Matrix-community -style user/chatlist (whichever possible) for telegram in ones contact list. Basically same thing that mautrix-facebook implements.

### PR DESCRIPTION
**Pull request by shukon**
Supposed to fix #365.
Basically just copied from https://github.com/tulir/mautrix-facebook/

It's working just fine for me, however there are quite a lot of changes (everything I could directly adapt from the facebook-bridge) and I was most certainly not always sure what I was doing. Worked surprisingly well to just copy stuff though, so there is that.

There were a few things I ignored, I don't know what they do and I couldn't find an equivalent in mautrix-telegram:

- [This in portal.py](https://github.com/tulir/mautrix-facebook/blob/6622191ce291fcc58f64cd8d4b7afdae8d1f7681/mautrix_facebook/portal.py#L496-L498) - I couldn't figure out how to appropriately put it in the method in mautrix-telegram
- [This in user.py](https://github.com/tulir/mautrix-facebook/blob/6622191ce291fcc58f64cd8d4b7afdae8d1f7681/mautrix_facebook/user.py#L459-L461) same as above, there is no thread-stuff in mautrix-telegram
- [This in commands/facebook.py](https://github.com/tulir/mautrix-facebook/blob/6622191ce291fcc58f64cd8d4b7afdae8d1f7681/mautrix_facebook/commands/facebook.py#L82)

### CODE REVIEW

**Comment by shukon** [comment]
Oh no. Just checked logs again and stumbled upon:
<details ErrorLog>
[2020-10-27 14:39:22,171] [INFO@telethon.-2488178757769453255.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
[2020-10-27 14:39:22,193] [ERROR@mau.portal.1240875543] Fatal error updating Matrix room
Traceback (most recent call last):
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    cursor, statement, parameters, context
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: mx_user_profile.room_id, mx_user_profile.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-test/mautrix_telegram/portal/metadata.py", line 193, in update_matrix_room
    await self._update_matrix_room(user, entity, direct, puppet, levels, users)
  File "/opt/mautrix-test/mautrix_telegram/portal/metadata.py", line 205, in _update_matrix_room
    await self._sync_telegram_users(user, users)
  File "/opt/mautrix-test/mautrix_telegram/portal/metadata.py", line 590, in _sync_telegram_users
    joined_mxids = await self.main_intent.get_room_members(self.mxid)
  File "/opt/mautrix-test/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 283, in get_room_members
    memberships = await self.get_joined_members(room_id)
  File "/opt/mautrix-test/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 91, in wrapper
    return await __method(*args, **kwargs)
  File "/opt/mautrix-test/lib/python3.7/site-packages/mautrix/client/store_updater.py", line 58, in get_joined_members
    await self.state_store.set_members(room_id, members, joined_only=True)
  File "/opt/mautrix-test/lib/python3.7/site-packages/mautrix/client/state_store/sqlalchemy/sqlstatestore.py", line 78, in set_members
    UserProfile.bulk_replace(room_id, members, joined_only=joined_only)
  File "/opt/mautrix-test/lib/python3.7/site-packages/mautrix/client/state_store/sqlalchemy/mx_user_profile.py", line 69, in bulk_replace
    for user_id, member in members.items()])
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    cursor, statement, parameters, context
  File "/opt/mautrix-test/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: mx_user_profile.room_id, mx_user_profile.user_id
[SQL: INSERT INTO mx_user_profile (room_id, user_id, membership, displayname, avatar_url) VALUES (?, ?, ?, ?, ?)]
[parameters: (('!eUQgjMFsfUwfEoyMSG:shukini.org', '@telegramfinaltestbot:shukini.org', 'JOIN', 'Telegram test bridge bot', 'mxc://maunium.net/tJCRmUyJDsgRNgqhOgoiHWbX'), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_184076767:shukini.org', 'JOIN', 'REDACTED (Telegram)', None), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_669027696:shukini.org', 'JOIN', 'REDACTED (Telegram)', None), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_352408506:shukini.org', 'JOIN', 'REDACTED (Telegram)', None), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_400045427:shukini.org', 'JOIN', 'REDACTED (Telegram)', 'mxc://shukini.org/QsuYzDytQXnsWXCmVGllJUpf'), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_239879937:shukini.org', 'JOIN', 'REDACTED (Telegram)', 'mxc://shukini.org/SJdsyAKXrBhbaeDqIGFiGTDd'), ('!eUQgjMFsfUwfEoyMSG:shukini.org', '@finaltest_telegram_205378583:shukini.org', 'JOIN', 'REDACTED (Telegram)', 'mxc://shukini.org/LQgkmBqxNmDMAYlbNthLgLPw'))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
</details>
(changed a few letters in the links because I have no idea what's sensible information, but kept up the general patterns)
... looks to me like some group creation issue, since it's all the same mxc-something-id-thing?

Also, sorry for the messy git-history :see_no_evil:

**Comment by shukon** [comment]
The error was not related to the changes of this PR and fixed in master already. So this is ready for review whenever you're ready @tulir 
I'm happy to fix issues, if you report any.

**Comment by shukon** [comment]
Would you prefer me to do a new PR with a clean(er) git history?
I will regularly pull from master to keep this up to date if you are cool with that.

**Comment by tulir** [comment]
Closing since this should be done properly with spaces, maybe including telegram folder sync

**Pull request closed without merging**
